### ISSUE TITLE
Tests failure - String does not understand #selector

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnectForRabbitMQ#1]
When executing tests via Jade against a new 3.6.4 database I get the error mentioned in the subject line.

It is shown in method _defectiveTestsIn: aClass (where a class = GsAmqpExampleTestCase). the local variable results is an instance of GsTestResult, but the instance variable "defects" is a NonPersistentArray of Strings ... and there the error goes on ....

**Comment by nrgiii** [comment]
![jade](https://user-images.githubusercontent.com/4521934/177659147-6a18eef9-6f33-41bc-bf26-20a464daa715.png)
Does not fail for me using latest Jade v2.4.21 . See attached screenshot. 
Can you specify exactly what steps you are doing more clearly?

**Comment by feldti** [comment]
I also use Jade 2.4.21, but even a simple (non tls) login does not work and I get a strange error:

In my case Jade connects to the database "testmq" at host "x" via port 40049 - and this is the netldi connection. When I execute

GsTsExternalSession newDefault login

I get the following error:

"error contacting GemService, NetLDi service 'gs64ldi' on node 'x' port 50377, not found ......."

So its tries to connect to a non existing netldi service - the default product specification for the netldi connection .... why that ?

I changed "/etc/services" so, the netldi service always gets the same port - but this does not change anything

Ok, the reason seems to be, that "GsNetworkResourceString defaultGemNRSFromCurrent asString" always returns the default connection information as "GsNetworkResourceString systemNetLDIName" does - and not the information based on the current connection.

The reason systemNetLDIName fails is, that it queries the environment variable "GEMSTONE_NRS_ALL" and there is no partial string "netldi" available, so it fallbacks to "gs64ldi"

Changing the code to (testmq_ldi is my current service in jade, nextgeneration is the name of the gemstone server): 

```
aGsTsExternalSession := GsTsExcternalSession newDefault.
aGsTsExternalSession parameters
   gemService: '!@nextgeneration#netldi:testmq_ldi#task!gemnetobject'.
 aGsTsExternalSession login
```
seems to work.

So how can this be fixed to get the correct gemService string from the current connection ? I never worked in this area ...

**Comment by feldti** [comment]
With the modification mentioned above I was able to run the tests and I could see the traffic in the Rabbit UI dashboard, so playing with RabbitMQ can start

**Comment by nrgiii** [comment]
I have confirmed the error "error contacting GemService, NetLDi service 'gs64ldi' on node 'x' port 50377, not found ......." and it is surprising to me that it does that. This may be a product bug in GsNetworkResourceString  and I will investigate further.
Another workout is to set this env var before starting your netldi:

export GEMSTONE_NRS_ALL="#netldi:testmq_ldi"

**Comment by nrgiii** [comment]
This is actually a bug (50046) in the GemStone product. We should be using the netldi start spawned the gem, not the one in GEMSTONE_NRS_ALL. This will be fixed in a future GemStone version
