### ISSUE TITLE
Does not work with DataCurator

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnectForRabbitMQ#3]
How can I make this library work under DataCurator ??? (e.g. GsDevKitHome)

**Comment by nrgiii** [comment]
Not sure why it would not. I can investigate. What error are you getting?

**Comment by feldti** [comment]
When I run the tests under SystemUser (after the modification in the other issue) they do run. If I execute these tests as DataCurator I get an SecurityError - perhaps its only related to the tests and not the connector itself.

An attempt was made to modify the object #debugEnabled-> false in objectSecurityPolicyId 1 with insufficient authorization

And I tried to install the GemConnect under DataCurator and that also leads to an error

**Comment by feldti** [comment]
The connector itself works under DataCurator - so I am fine with this.
