### ISSUE TITLE
How to access vhosts in RabbitMQ ?

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnectForRabbitMQ#4]
This is perhaps more a question about programming - but how can I access a specific vhost via your code ?

**Comment by nrgiii** [comment]
Right now it only supports the default vhost of $/ . Your request is reasonable and I will work on adding support for non-default vhosts in the next version.

**Comment by feldti** [comment]
That's wonderful ... then I will support this also in my code generator

**Comment by nrgiii** [comment]
Add support for non-default vhosts
