### ISSUE TITLE
GsAmqpMethod>>decodeMethodObject - channelClose

### ISSUE THREAD

**Issue by feldti** [GemTalk/GemConnectForRabbitMQ#5]
This is the last test in that method ... the statement in the following block should return at once as the other tests in the method are doing ... otherwise is runs to self error: ....

	self isChannelClose
		ifTrue: "broker closed the connection, raise an exception"
			[ GsAmqpChannelClose fromMemoryReferenceIn: self atOffset: 8.
			"| close |
			close := GsAmqpChannelClose fromMemoryReferenceIn: self atOffset: 8.
			^(GsRabbitMqError newFromChannelClose: close) signal"
		].

**Comment by nrgiii** [comment]
Fix as suggested.
